version: "2"
run:
  modules-download-mode: readonly
  issues-exit-code: 1
linters:
  default: none
  enable:
    - bodyclose
    - contextcheck
    - errcheck
    - gocritic
    - gosec
    - govet
    - misspell
    - nakedret
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - unused
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
    govet:
      disable:
        - fieldalignment
      enable-all: true
    revive:
      severity: error
      rules:
        - name: exported
          arguments: []
        - name: package-comments
          disabled: false
  exclusions:
    generated: lax
    paths:
      - internal/store/dbgen
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
  new: false
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/alexchristy/SpaceATracker
  exclusions:
    generated: lax
    paths:
      - internal/store/dbgen
      - third_party$
      - builtin$
      - examples$
