services:
  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - internal_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    build: .
    command:
      - /bin/migrate
      - -path=/db/migrations
      - -database=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
      - up
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal_network

  worker:
    build: ./ 
    command:
      - /bin/worker
    depends_on:
      migrate:
        condition: service_completed_successfully 
    environment:
      - TERMINAL_INDEX_URL
      - SCRAPER_API_KEY
      - DISCOVERY_INTERVAL

      - DATABASE_URI=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable

      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_PROTOCOL
      - OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_RESOURCE_ATTRIBUTES

    networks:
      - internal_network

volumes:
  postgres_data:

networks:
  internal_network:
    driver: bridge
