// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package dbgen

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const upsertTerminals = `-- name: UpsertTerminals :batchexec
INSERT INTO discovered_terminals (url)
VALUES ($1)
ON CONFLICT (url)
DO UPDATE SET url = EXCLUDED.url
`

type UpsertTerminalsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

func (q *Queries) UpsertTerminals(ctx context.Context, url []string) *UpsertTerminalsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range url {
		vals := []interface{}{
			a,
		}
		batch.Queue(upsertTerminals, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertTerminalsBatchResults{br, len(url), false}
}

func (b *UpsertTerminalsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertTerminalsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
