name: govulncheck

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "go.mod"
      - "go.sum"
      - ".github/workflows/govulncheck.yml"
      - "**/*.go"
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  schedule:
    - cron: '0 4 * * 1'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Run govulncheck
        uses: golang/govulncheck-action@v1
        with:
          check-latest: true
