name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "go.mod"
      - "go.sum"
      - ".github/workflows/unit-tests.yml"
      - "**/*.go"
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      
      - uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Run tests
        run: go test -race -shuffle=on ./...
